### ISSUE TITLE
Setupt timeout on curl

### ISSUE THREAD

**Issue by GregsGerard** [alma/alma-php-client#11]
It would be a nice feature to have a customizable way to set up a specific timeout on curl in order to avoid errors

**Comment by webaaz** [comment]
Hi @GregsGerard what is your problem ? do you have a bad connection? We do not feel this need on our side. can you tell us what exactly you need?

**Comment by bastien-effetb** [comment]
+1 it would allow more control when integrating your solution in a multi payment means page. By doing so if for any reason the connexion take longer than 5 seconds (or whatever we think acceptable) we can show other payment means and do not display Alma. With the current config we need to display them by using an ajax request to prevent any blocking.
