### ISSUE TITLE
PSR 4 Warning Test Classes

### ISSUE THREAD

**Issue by Kwaadpepper** [alma/alma-php-client#30]
Just installed with composer, and it seems some test classes are not PS4 valid

      Class Alma\API\Tests\Integration\PaymentsTest located in ./vendor/alma/alma-php-client/tests/integration/Endpoints/PaymentTest.php does not comply with psr-4 autoloading standard. Skipping.
      Class Alma\API\Tests\Unit\PaymentsTest located in ./vendor/alma/alma-php-client/tests/unit/Endpoints/PaymentsTest.php does not comply with psr-4 autoloading standard. Skipping.
      Class Alma\API\Tests\ClientContextTest located in ./vendor/alma/alma-php-client/tests/unit/ClientContextTest.php does not comply with psr-4 autoloading standard. Skipping.
      Class Alma\API\Tests\ArrayUtilsTest located in ./vendor/alma/alma-php-client/tests/unit/ArrayUtilsTest.php does not comply with psr-4 autoloading standard. Skipping.
      Class Alma\API\Tests\ClientOptionsValidatorTest located in ./vendor/alma/alma-php-client/tests/unit/ClientOptionsValidatorTest.php does not comply with psr-4 autoloading standard. Skipping.

**Comment by francoisdelage** [comment]
+1

**Comment by francoisdelage** [comment]
This issue should now be closed: https://github.com/alma/alma-php-client/releases/tag/v1.9.2
Thanks
