### ISSUE TITLE
Add support for Psr/Log v2/3

### ISSUE THREAD

**Issue by NicolasGraph** [alma/alma-php-client#46]
I recently developped the [commerce_alma](https://www.drupal.org/project/commerce_alma) module for Drupal Commerce. I'd like to make it available for Drupal 10, however, as D10 now requires Psr/Log v3, the Alma API client install fails.

**Comment by NicolasGraph** [comment]
Here's the [PR](https://github.com/alma/alma-php-client/pull/47).

**Comment by NicolasGraph** [comment]
psr/log ^2.0 was also added to the pull request as suggested by @dunglas to be supported by Sylius.

**Comment by villfa** [comment]
@ClaireAlma Is it possible to consider creating alma-php-client V2 which will support psr/log v2/v3?
I know that maintaining 2 branches doubles the work, but the constraint on psr/log is more and more blocking.

For instance it prevents tu upgrade to [Laravel 10](https://packagist.org/packages/laravel/framework), because it requires [monolog v3](https://packagist.org/packages/monolog/monolog) which requires psr/log v2 at minimum.

**Comment by ClaireAlma** [comment]
Hi @villfa we will study that, I'll get back to you soon

**Comment by dunglas** [comment]
@ClaireAlma with a constraint like `"psr/log": "^1 || ^2 || ^3"`, you will be able to support all PHP versions you want in the same branch. Composer will automatically download the appropriate version.

**Comment by villfa** [comment]
I wanted to open a PR with the change proposed by by @dunglas but I was able to test it only with PHP 5.6, so instead I have open this PR: https://github.com/alma/alma-php-client/pull/54
Thanks in advance for reviewing it 🙏

**Comment by villfa** [comment]
For the record, the change proposed by @dunglas is not enough.
When a newer version of `psr/log` is installed, it produces the following error:
```
PHP Fatal error:  Declaration of Alma\API\Client::setLogger(Psr\Log\LoggerInterface $logger) must be compatible with Psr\Log\LoggerAwareInterface::setLogger(Psr\Log\LoggerInterface $logger): void in /home/runner/work/alma-php-client/alma-php-client/src/Client.php on line 166
```

That's why I initially proposed to have 2 branches. It will require small changes and bumping to a new major version won't cause any issue to users.
